import "./globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {" "}
        <div>
          {/* @ts-expect-error Server Component */}
          <Sidebar />
        </div>
        <div className="ml-[200px] h-full p-[50px]">{children}</div>
      </body>
    </html>
  );
}
